yml updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,46 +18,10 @@ jobs:
             - run: gem install bundler:2.1.4
             - run: bundle install
             - run:
-                name: Install libs for libpulse
-                command: |
-                        cd
-                        sudo apt-get update
-                        sudo apt-get install pulseaudio
-            - run:
-                name: List Images
-                command: sdkmanager --list --verbose | grep system-images
-            - run:
-                name: Setup Emulator
-                command: sdkmanager "system-images;android-29;default;armeabi-v7a" && echo
-                    "no" | avdmanager create avd -n test -k "system-images;android-29;default;armeabi-v7a"
-            - run:
-                name: Launch Emulator
-                command: |
-                    cd ${ANDROID_HOME}/emulator;ls
-                    export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
-                    emulator -avd test -skin 1440x2560 -no-window -noaudio -no-boot-anim -no-window -accel on
-                background: true
-            - run:
-                name: Wait emulator
-                command: |
-                    circle-android wait-for-boot
-                    adb shell input keyevent 82
-            - run:
-                name: Install Node
-                command: |
-                    cd
-                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
-                    sudo apt install nodejs
-            - run:
-                name: Print Node and NPM Version
-                command: |
-                    node --version
-                    npm --version
-            - run:
                 name: Install Appium
                 command: |
                     cd
-                    npm install appium@1.14.0
+                    npm install appium@1.17.0
             - run:
                 name: Start Appium
                 command: cd ; appium
@@ -65,15 +29,34 @@ jobs:
             - run:
                 name: Wait Until Appium Boot
                 command: sleep 30
-            - checkout
+
+                # Generate apk
+            - run: ./gradlew assembleDebug
+
+# Upload app to BrowserStack and set app url in an environment variable.
+# Here replace app-debug.apk with name of your apk.
+            - run:
+                name : App upload and Set app id in environment variable.
+                command : |
+                  APP_UPLOAD_RESPONSE=$(curl -u "siva518:UQZfAXgr43CUqsZKxhF6" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/mobile_apps/naukri.apk")
+                  APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+                  if [ $APP_ID != null ]; then
+                  echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+                  echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+                  source $BASH_ENV;
+                  echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+                  else
+                  UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+                  echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+                  exit 1;
+                  fi
+
+# run tests!
+            - run: ./gradlew test
+              - checkout
             - run:
                 name: Install APK
                 command: adb install naukri.apk
             - run:
                 name: Run Tests
                 command: bundle exec cucumber -p mobile
-            - store_test_results:
-                path: target/surefire-reports
-            - store_artifacts:
-                path: target/surefire-reports
-                destination: sanity-test-results
